# Generated by Django 6.0 on 2025-12-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receipe',
        ),
    ]
